---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: shopverse-ecommerce-project-payment:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
