---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: shopverse
spec:
  selector:
    app: payment
  ports:
    - port: 3004
      targetPort: 3004
      nodePort: 30060
  type: NodePort
