services:
  auth:
    build:
      context: ./services/auth
    container_name: auth
    ports:
      - "3000:3000"
    networks:
      - shopverse-net
    restart: unless-stopped
    env_file:
      - ./services/auth/.env

  product:
    build:
      context: ./services/product
    container_name: product
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/product_db
    networks:
      - shopverse-net
    restart: unless-stopped
    env_file:
      - ./services/product/.env

  cart:
    build:
      context: ./services/cart
    container_name: cart
    ports:
      - "3002:3002"
    networks:
      - shopverse-net
    restart: unless-stopped
    env_file:
      - ./services/cart/.env

  order:
    build:
      context: ./services/order
    container_name: order
    ports:
      - "3003:3003"
    networks:
      - shopverse-net
    restart: unless-stopped
    env_file:
      - ./services/order/.env

  payment:
    build:
      context: ./services/payment
    container_name: payment
    ports:
      - "3004:3004"
    networks:
      - shopverse-net
    restart: unless-stopped

  frontend:
    build:
      context: ./services/frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_AUTH=http://auth:3000
      - VITE_API_PRODUCT=http://product:3001
      - VITE_API_CART=http://cart:3002
      - VITE_API_ORDER=http://order:3003
      - VITE_API_PAYMENT=http://payment:3004
    depends_on:
      - auth
      - product
      - cart
      - order
      - payment
    networks:
      - shopverse-net

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - shopverse-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  mongo_data:

networks:
  shopverse-net:
    driver: bridge
 
