---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: shopverse-ecommerce-project-product:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: product-config
