---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: shopverse
spec:
  selector:
    app: product
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30070
  type: NodePort
