---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: shopverse-ecommerce-project-auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
