---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: shopverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: shopverse-ecommerce-project-order:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: order-config
