---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: shopverse
spec:
  selector:
    app: order
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30050
  type: NodePort
